/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mc_player.views;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JButton;

/**
 *
 * @author SGI
 */
public class DownBar extends javax.swing.JPanel {

    /**
     * Creates new form DownBar
     */
    public DownBar() {
        initComponents();
        init();
        setOpaque(false);
        setBackground(new Color(68,68,68));
    }
  @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2=(Graphics2D)g;
        g2.setColor(getBackground());
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
        g2.fillRoundRect(0, 0,getWidth(),getHeight(), 20, 20);
        super.paintComponent(g);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        slider1 = new mc_player.views.Slider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc_player/icons/back.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc_player/icons/next.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusable(false);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc_player/icons/pauseit.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusable(false);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        slider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                slider1MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("00:00");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("00:00");

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc_player/icons/love_bot.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slider1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(0, 0, 0)
                .addComponent(jButton7)
                .addGap(0, 0, 0)
                .addComponent(jButton5)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(slider1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
       private Integer count=1;
    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
       if(count==0){
       jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc_player/icons/pauseit.png")));
       count=1;}
       else{
       jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc_player/icons/playit.png")));
       count=0;
       }
       
    }//GEN-LAST:event_jButton7MouseClicked
    public JButton getButtonLike(){return jButton8;}
    public JButton getButtonPlay(){return jButton7;}
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void slider1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_slider1MousePressed
    public void setSlideValue(int n){
        slider1.setValue(n);
    }
    public Slider getSlider(){return slider1;}
    private void init(){
        slider1.setValue(0);
    }
    public void setEnd(int d){
        Integer minutes=d/60;
        Integer secondes=d%60;
        String duration="";
        if(minutes<10 && secondes<10){
        duration="0"+String.valueOf(minutes)+":"+"0"+String.valueOf(secondes);
        }
        else if(secondes<10){
        duration=String.valueOf(minutes)+":"+"0"+String.valueOf(secondes);
        }
        else if(minutes<10){
        duration="0"+String.valueOf(minutes)+":"+String.valueOf(secondes);
        }
        else{
        duration=String.valueOf(minutes)+":"+String.valueOf(secondes);
        }
        jLabel3.setText(duration);
    }
    public void setDeb(int d){
        Integer minutes=d/60;
        Integer secondes=d%60;
        String duration="";
        if(minutes<10 && secondes<10){
        duration="0"+String.valueOf(minutes)+":"+"0"+String.valueOf(secondes);
        }
        else if(secondes<10){
        duration=String.valueOf(minutes)+":"+"0"+String.valueOf(secondes);
        }
        else if(minutes<10){
        duration="0"+String.valueOf(minutes)+":"+String.valueOf(secondes);
        }
        else{
        duration=String.valueOf(minutes)+":"+String.valueOf(secondes);
        }
        jLabel2.setText(duration);
    }
    public JButton getButtonNext(){return jButton5;}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private mc_player.views.Slider slider1;
    // End of variables declaration//GEN-END:variables
}
