/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mc_player.views;

import mc_player.models.Music_Model;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author SGI
 */
public class MainMusic_Playlist extends javax.swing.JPanel {
ArrayList<String> al;
    /**
     * Creates new form MainMusic
     */
    public ListMusic getList(){return listMusic1;}
    public MainMusic_Playlist() {
        try {
            initComponents();
            init();
        } catch (Exception ex) {
            Logger.getLogger(MainMusic_Playlist.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public ListMusic<String> getListMusic1() {
        return listMusic1;
    }
    public void init() throws FileNotFoundException, IOException {
        MP3Player mp3Player=new MP3Player();
        listMusic1.addListSelectionListener(new ListSelectionListener(){
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if(!e.getValueIsAdjusting()){
            Integer index=listMusic1.getSelectedIndex();
            if(index !=-1){
                //imageData=mp3Player.extractImage(al.get(index));
                //setFrames(mp3Player.extractFrames(al.get(index)));
                mp3Player.setFilename(al.get(index));
                mp3Player.stop();
                //mp3Player.play();
                //setLength(mp3Player.extractLength(al.get(index)));
                
            }
            }
             SwingUtilities.invokeLater(()->{
            listMusic1.setVisible(false);
            listMusic1.repaint();
            listMusic1.setVisible(true);
             });
        }
    });
    al=new ArrayList<>();
          Path pth =Paths.get("C:","Users","DELL","Documents","NetBeansProjects","MC_Player","src","mc_player","putsong","liked.txt");
      try(BufferedReader reader=new BufferedReader(new FileReader(pth.toFile()))){
        String line;
        Integer no=1;
        while((line=reader.readLine())!=null){
        String title=mp3Player.extractMetaData(line);
        Integer length=mp3Player.extractLength(line);
        Integer minutes=length/60;
        Integer secondes=length%60;
        String duration="00:00";
        if(minutes<10 && secondes<10){
        duration="0"+String.valueOf(minutes)+":"+"0"+String.valueOf(secondes);
        }
        else if(secondes<10){
        duration=String.valueOf(minutes)+":"+"0"+String.valueOf(secondes);
        }
        else if(minutes<10){
        duration="0"+String.valueOf(minutes)+":"+String.valueOf(secondes);
        }
        else{
        duration=String.valueOf(minutes)+":"+String.valueOf(secondes);
        }
        if(title.length()!=0){
        if(title.length()>65){
        StringBuilder sb=new StringBuilder();
        for(int i=0;i<53;i++){
        sb.append(title.charAt(i));
        }
        sb.append("...");
        listMusic1.addItem(new Music_Model(String.valueOf(no),sb.toString(),duration));
        al.add(line);
        no++;
        }
        else{
        listMusic1.addItem(new Music_Model(String.valueOf(no),title,duration));
        al.add(line);
        no++;        }}
        }
        }
    }

    public ListPlayLists<String> getListPlayLists1() {
        return listPlayLists1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listMusic1 = new mc_player.views.ListMusic<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPlayLists1 = new mc_player.views.ListPlayLists<>();

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Feel the music Listen Now");

        listMusic1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Liked songs");

        jScrollPane1.setHorizontalScrollBar(new ScrollBar());

        listPlayLists1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "item1", "item1", "item1", "item1", "item1", "item1", "item1", "item1", "item1", "item1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listPlayLists1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listPlayLists1.setToolTipText("");
        jScrollPane1.setViewportView(listPlayLists1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listMusic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listMusic1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private mc_player.views.ListMusic<String> listMusic1;
    private mc_player.views.ListPlayLists<String> listPlayLists1;
    // End of variables declaration//GEN-END:variables
}
